version: 1

screenshots:
  - name: home-mobile
    url: http://localhost:3000/
    viewport:
      width: 375
      height: 812
    waitFor: .task-list

  - name: add-task-desktop
    url: http://localhost:3000/
    viewport:
      width: 1280
      height: 800
    steps:
      - click: "[data-testid='add-task-button']"
      - waitFor: "[data-testid='task-form']"

  - name: home-desktop
    url: http://localhost:3000/
    viewport:
      width: 1280
      height: 800
    waitFor: .task-list

  - name: home-mobile
    url: http://localhost:3000/
    viewport:
      width: 375
      height: 812
    waitFor: .task-list

  - name: add-task-desktop
    url: http://localhost:3000/
    viewport:
      width: 1280
      height: 800
    steps:
      - click: "[data-testid='add-task-button']"
      - waitFor: "[data-testid='task-form']"

output:
  branch: gh-screenshots
  comment:
    template: default
    group_by: viewport