version: 1

screenshots:
  - name: home-desktop
    url: http://localhost:3000/
    viewport:
      width: 1280
      height: 800
    waitFor: .task-list

  - name: home-mobile
    url: http://localhost:3000/
    viewport:
      width: 375
      height: 812
    waitFor: .task-list

  - name: fab-opened-mobile
    url: http://localhost:3000/
    viewport:
      width: 375
      height: 812
    steps:
      - waitFor: .task-list
      - click: ".fixed.bottom-6.right-6 button"
      - wait: 300

  - name: fab-camera-mobile
    url: http://localhost:3000/
    viewport:
      width: 375
      height: 812
    steps:
      - waitFor: .task-list
      - click: ".fixed.bottom-6.right-6 button"
      - wait: 300
      - click: "[data-testid='fab-camera']"
      - wait: 500

  - name: fab-microphone-mobile
    url: http://localhost:3000/
    viewport:
      width: 375
      height: 812
    steps:
      - waitFor: .task-list
      - click: ".fixed.bottom-6.right-6 button"
      - wait: 300
      - click: "[data-testid='fab-microphone']"
      - wait: 500

  - name: fab-keyboard-mobile
    url: http://localhost:3000/
    viewport:
      width: 375
      height: 812
    steps:
      - waitFor: .task-list
      - click: ".fixed.bottom-6.right-6 button"
      - wait: 300
      - click: "[data-testid='fab-keyboard']"
      - wait: 500

  - name: single-task-view-mobile
    url: http://localhost:3000/
    viewport:
      width: 375
      height: 812
    steps:
      - waitFor: .task-list
      - click: "[data-task-id]:first-child"
      - waitFor: "h1:has-text('Task Details')"
      - wait: 500

output:
  branch: gh-screenshots
  comment:
    template: default
    group_by: viewport