# Railway auto-detects this file for Next.js
[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-10_x"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"