codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...90"
  
  status:
    project:
      default:
        # Overall project coverage
        target: 80%
        threshold: 2%  # Allow 2% drop in coverage
        base: auto
        if_not_found: success
        if_ci_failed: error
        
    patch:
      default:
        # Coverage for new/modified code in PR
        target: 75%  # New code should have at least 75% coverage
        threshold: 5%  # Allow 5% wiggle room
        base: auto
        if_not_found: success
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  # Ignore test files and examples
  - "*/test_*.py"
  - "*/tests/**"
  - "*/examples/**"
  - "**/migrations/**"
  - "**/__pycache__/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"