# Railway auto-detects this file and uses Nixpacks builder
[phases.setup]
nixPkgs = ["python313", "uv"]

[phases.install]
cmds = ["uv sync"]

[start]
cmd = "uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT"