[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "python-dotenv>=1.1.1",
    "supabase>=2.17.0",
    "uvicorn[standard]>=0.35.0",
]

[tool.uv.dev-dependencies]
test = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=6.0.0",
    "pytest-env>=1.1.5",
    "httpx>=0.28.1",
    "pytest-mock>=3.14.0",
]
