"""Add name and avatar_url to users table

Revision ID: 2c45598d0a4f
Revises: 2f14bca5bdda
Create Date: 2025-08-07 18:42:53.868457

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c45598d0a4f"
down_revision = "2f14bca5bdda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("avatar_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
