"""Add locale preference column to users

Revision ID: 2f14bca5bdda
Revises: b234fa5b123c
Create Date: 2025-08-05 18:33:43.759682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f14bca5bdda'
down_revision = 'b234fa5b123c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale_preference', sa.String(length=10), nullable=True, comment="User's preferred locale (e.g., 'en', 'he')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale_preference')
    # ### end Alembic commands ###